# Generated by Django 4.0.3 on 2022-04-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_customer_totalamount_customercheckout_totalamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombook',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roombook',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
