# Generated by Django 4.0.3 on 2022-04-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_roombook_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombook',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
