# Generated by Django 4.0.3 on 2022-04-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_roombook_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombook',
            name='check_out_status',
            field=models.BooleanField(default=False),
        ),
    ]
